all:
  children:
    domain_controllers:
      hosts:
        dc01:
          ansible_host: 192.168.1.220
    member_servers:
      hosts:
        mgmt01:
          ansible_host: 192.168.1.221
        ws01:
          ansible_host: 192.168.1.223
  vars:
    ansible_user: cparent-adm
    ansible_connection: winrm
    ansible_winrm_transport: ntlm
    ansible_winrm_server_cert_validation: ignore
    ansible_port: 5986
